
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/var/lib/snapd/snap/clion/314/bin/cmake/linux/x64/share/cmake-3.30/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.12.11-200.fc41.x86_64 - x86_64
...
